
title: Shehab Mohamed
url: 'http://shehabce.github.io'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2   #lime green
#style: styles-3  #Green
style: styles-4  #Purple
#style: styles-5  #Orange
#style: styles-6  #Grey


#Profile information
name: Shehab Mohamed
tagline: Software Developer
pic: profile.jpeg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: shehab_m@aucegypt.edu
#phone: 
website: shehabce.github.io #do not add http://
linkedin: shehab-abdel-salam-0a12ab97/
github: ShehabCE
#twitter: ''


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
